name: 'Azure Vote Canary Deployment'

on:
  push:
    branches:
      - main

jobs:
  deploy-canary:
    name: 'Deploy Canary'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Login via Azure CLI'
      run: az login --tenant ${{ secrets.AZURE_TENANT_ID }} -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }}   

    - name: 'Set up kubectl'
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
        sudo apt-get update
        sudo apt-get install -y kubectl
        sudo snap install kubectl --classic

    - name: 'Configure kubectl'
      run: helm lint ./vote-app-deployment

    - name: 'deployement'
      run: helm install --dry-run --debug my-vote-app ./vote-app-deployment

    - name: 'recuperer le nom du pod && recupérer le port du conteneur && rediriger le port'
      run: |
        export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=vote-app-deployment,app.kubernetes.io/instance=my-vote-app" -o jsonpath="{.items[0].metadata.name}")
        export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
        kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT

    - name: 'Deploy Canary Release'
      run: kubectl apply -f canary-release.yaml
