name: 'Terraform CI/CD'

on:
  push:
    branches:
    - main

jobs:
  terraform:
    name: 'Terraform init validate plan'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip

    - name: install azure cli
      run: pip install azure-cli

    - name: 'Login via Azure CLI'
      run: az login --tenant ${{ secrets.AZURE_TENANT_ID }} -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }}

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Validate'
      run: terraform validate

    - name: 'Terraform Plan'
      run: terraform plan
