name: 'Terraform CI/CD'

on:
  push:
    branches:
    - main

jobs:
  terraform:
    name: 'Pipeline CI/CD'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install Python'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip

    - name: 'Install Azure cli'
      run: pip install azure-cli

    - name: 'Login via Azure CLI'
      run: az login --tenant ${{ secrets.AZURE_TENANT_ID }} -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }}

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Validate'
      run: terraform validate

    - name: 'Terraform Plan'
      run: terraform plan

    - name: 'Install Infracost'
      run: |
        curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh    

    - name: 'Run Infracost'
      run: |
        infracost breakdown --path . --format json --out-file /tmp/infracost.json
      env:
        INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

    - name: 'Upload Infracost result'
      run: |
        infracost output --path /tmp/infracost.json --format github-comment > infracost-comment.md
        cat infracost-comment.md

    - name: 'Verif Terraform apply'
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.TOKEN }}
        approvers: fologix       
        minimum-approvals: 1
        issue-title: "Besoin d une validation humaine appliquer !"
        issue-body: "Please approve or deny the apply"
        exclude-workflow-initiator-as-approver: false

    - name: Terraform Apply
      run: terraform apply -auto-approve

